<?php
require_once __DIR__ . '/../config.php';

$cities = [
    ['REGION XIII', 'AGUSAN DEL NORTE', 'Butuan City'],
    ['REGION XIII', 'AGUSAN DEL NORTE', 'Cabadbaran City'],
    ['REGION XIII', 'AGUSAN DEL NORTE', 'Buenavista'],
    ['REGION XIII', 'AGUSAN DEL NORTE', 'Carmen'],
    ['REGION XIII', 'AGUSAN DEL NORTE', 'Jabonga'],
    ['REGION XIII', 'AGUSAN DEL NORTE', 'Kitcharao'],
    ['REGION XIII', 'AGUSAN DEL NORTE', 'Las Nieves'],
    ['REGION XIII', 'AGUSAN DEL NORTE', 'Magallanes'],
    ['REGION XIII', 'AGUSAN DEL NORTE', 'Nasipit'],
    ['REGION XIII', 'AGUSAN DEL NORTE', 'Remedios T. Romualdez'],
    ['REGION XIII', 'AGUSAN DEL NORTE', 'Santiago'],
    ['REGION XIII', 'AGUSAN DEL NORTE', 'Tubay'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'Bayugan'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'Bunawan'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'Esperanza'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'La Paz'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'Loreto'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'Prosperidad'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'Rosario'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'San Francisco'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'San Luis'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'Santa Josefa'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'Sibagat'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'Talacogon'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'Trento'],
    ['REGION XIII', 'AGUSAN DEL SUR', 'Veruela'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Surigao City'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Alegria'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Bacuag'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Burgos'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Claver'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Dapa'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Del Carmen'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'General Luna'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Gigaquit'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Mainit'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Malimano'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Pilar'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Placer'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'San Benito'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'San Francisco'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'San Isidro'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Santa Monica'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Sison'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Socorro'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Tagana-an'],
    ['REGION XIII', 'SURIGAO DEL NORTE', 'Tubod'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Bislig City'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Tandag City'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Barobo'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Bayabas'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Cagwait'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Cantilan'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Carmen'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Carrascal'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Cortes'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Hinatuan'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Lanuza'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Lianga'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Lingig'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Madrid'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Marihatag'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'San Agustin'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'San Miguel'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Tagbina'],
    ['REGION XIII', 'SURIGAO DEL SUR', 'Tago'],
    ['REGION XIII', 'DINAGAT ISLANDS', 'Basilisa (Rizal)'],
    ['REGION XIII', 'DINAGAT ISLANDS', 'Cagdianao'],
    ['REGION XIII', 'DINAGAT ISLANDS', 'Dinagat'],
    ['REGION XIII', 'DINAGAT ISLANDS', 'Libjo (Albor)'],
    ['REGION XIII', 'DINAGAT ISLANDS', 'Loreto'],
    ['REGION XIII', 'DINAGAT ISLANDS', 'San Jose'],
    ['REGION XIII', 'DINAGAT ISLANDS', 'Tubajon'],
    ['BARMM', 'BASILAN', 'Isabela City'],
    ['BARMM', 'BASILAN', 'Lamitan City'],
    ['BARMM', 'BASILAN', 'Akbar'],
    ['BARMM', 'BASILAN', 'Al-Barka'],
    ['BARMM', 'BASILAN', 'Hadji Mohammad Aju'],
    ['BARMM', 'BASILAN', 'Lantawan'],
    ['BARMM', 'BASILAN', 'Maluso'],
    ['BARMM', 'BASILAN', 'Sumisip'],
    ['BARMM', 'BASILAN', 'Tipo-Tipo'],
    ['BARMM', 'BASILAN', 'Tuburan'],
    ['BARMM', 'BASILAN', 'Ungkaya Pukan'],
    ['BARMM', 'LANAO DEL SUR', 'Marawi City'],
    ['BARMM', 'LANAO DEL SUR', 'Bacolod-Kalawi'],
    ['BARMM', 'LANAO DEL SUR', 'Balabagan'],
    ['BARMM', 'LANAO DEL SUR', 'Balindong'],
    ['BARMM', 'LANAO DEL SUR', 'Bayang'],
    ['BARMM', 'LANAO DEL SUR', 'Binidayan'],
    ['BARMM', 'LANAO DEL SUR', 'Buadiposo-Buntong'],
    ['BARMM', 'LANAO DEL SUR', 'Bubong'],
    ['BARMM', 'LANAO DEL SUR', 'Bumbaran'],
    ['BARMM', 'LANAO DEL SUR', 'Butig'],
    ['BARMM', 'LANAO DEL SUR', 'Calanogas'],
    ['BARMM', 'LANAO DEL SUR', 'Ditsaan-Ramain'],
    ['BARMM', 'LANAO DEL SUR', 'Ganassi'],
    ['BARMM', 'LANAO DEL SUR', 'Kapai'],
    ['BARMM', 'LANAO DEL SUR', 'Kapatagan'],
    ['BARMM', 'LANAO DEL SUR', 'Lumba-Bayabao'],
    ['BARMM', 'LANAO DEL SUR', 'Lumbaca-Unayan'],
    ['BARMM', 'LANAO DEL SUR', 'Lumbatan'],
    ['BARMM', 'LANAO DEL SUR', 'Lumbayanague'],
    ['BARMM', 'LANAO DEL SUR', 'Madalum'],
    ['BARMM', 'LANAO DEL SUR', 'Madamba'],
    ['BARMM', 'LANAO DEL SUR', 'Maguing'],
    ['BARMM', 'LANAO DEL SUR', 'Malabang'],
    ['BARMM', 'LANAO DEL SUR', 'Marantao'],
    ['BARMM', 'LANAO DEL SUR', 'Marogong'],
    ['BARMM', 'LANAO DEL SUR', 'Masiu'],
    ['BARMM', 'LANAO DEL SUR', 'Mulondo'],
    ['BARMM', 'LANAO DEL SUR', 'Pagayawan'],
    ['BARMM', 'LANAO DEL SUR', 'Piagapo'],
    ['BARMM', 'LANAO DEL SUR', 'Poona Bayabao'],
    ['BARMM', 'LANAO DEL SUR', 'Pualas'],
    ['BARMM', 'LANAO DEL SUR', 'Saguiaran'],
    ['BARMM', 'LANAO DEL SUR', 'Sultan Dumalondong'],
    ['BARMM', 'LANAO DEL SUR', 'Picong'],
    ['BARMM', 'LANAO DEL SUR', 'Tagoloan II'],
    ['BARMM', 'LANAO DEL SUR', 'Tamparan'],
    ['BARMM', 'LANAO DEL SUR', 'Taraka'],
    ['BARMM', 'LANAO DEL SUR', 'Tubaran'],
    ['BARMM', 'LANAO DEL SUR', 'Tugaya'],
    ['BARMM', 'LANAO DEL SUR', 'Wao'],
    ['BARMM', 'MAGUINDANAO', 'Cotabato City'],
    ['BARMM', 'MAGUINDANAO', 'Ampatuan'],
    ['BARMM', 'MAGUINDANAO', 'Buluan'],
    ['BARMM', 'MAGUINDANAO', 'Datu Abdullah Sangki'],
    ['BARMM', 'MAGUINDANAO', 'Datu Anggal Midtimbang'],
    ['BARMM', 'MAGUINDANAO', 'Datu Paglas'],
    ['BARMM', 'MAGUINDANAO', 'Datu Piang'],
    ['BARMM', 'MAGUINDANAO', 'Datu Saudi-Ampatuan'],
    ['BARMM', 'MAGUINDANAO', 'Datu Unsay'],
    ['BARMM', 'MAGUINDANAO', 'Gen. S. K. Pendatun'],
    ['BARMM', 'MAGUINDANAO', 'Guindulungan'],
    ['BARMM', 'MAGUINDANAO', 'Mamasapano'],
    ['BARMM', 'MAGUINDANAO', 'Mangudadatu'],
    ['BARMM', 'MAGUINDANAO', 'Pagagawan'],
    ['BARMM', 'MAGUINDANAO', 'Pagalungan'],
    ['BARMM', 'MAGUINDANAO', 'Paglat'],
    ['BARMM', 'MAGUINDANAO', 'Pandag'],
    ['BARMM', 'MAGUINDANAO', 'Rajah Buayan'],
    ['BARMM', 'MAGUINDANAO', 'Shariff Aguak'],
    ['BARMM', 'MAGUINDANAO', 'South Upi'],
    ['BARMM', 'MAGUINDANAO', 'Sultan sa Barongis'],
    ['BARMM', 'MAGUINDANAO', 'Talayan'],
    ['BARMM', 'MAGUINDANAO', 'Talitay'],
    ['BARMM', 'MAGUINDANAO', 'Barira'],
    ['BARMM', 'MAGUINDANAO', 'Buldon'],
    ['BARMM', 'MAGUINDANAO', 'Datu Blah T. Sinsuat'],
    ['BARMM', 'MAGUINDANAO', 'Datu Odin Sinsuat'],
    ['BARMM', 'MAGUINDANAO', 'Kabuntalan'],
    ['BARMM', 'MAGUINDANAO', 'Matanog'],
    ['BARMM', 'MAGUINDANAO', 'Northern Kabuntalan'],
    ['BARMM', 'MAGUINDANAO', 'Parang'],
    ['BARMM', 'MAGUINDANAO', 'Sultan Kudarat'],
    ['BARMM', 'MAGUINDANAO', 'Sultan Mastura'],
    ['BARMM', 'MAGUINDANAO', 'Upi'],
    ['BARMM', 'SULU', 'Hadji Panglima Tahil'],
    ['BARMM', 'SULU', 'Indanan'],
    ['BARMM', 'SULU', 'Jolo'],
    ['BARMM', 'SULU', 'Kalingalan Caluang'],
    ['BARMM', 'SULU', 'Lugus'],
    ['BARMM', 'SULU', 'Luuk'],
    ['BARMM', 'SULU', 'Maimbung'],
    ['BARMM', 'SULU', 'Old Panamao'],
    ['BARMM', 'SULU', 'Omar'],
    ['BARMM', 'SULU', 'Pandami'],
    ['BARMM', 'SULU', 'Panglima Estino'],
    ['BARMM', 'SULU', 'Pangutaran'],
    ['BARMM', 'SULU', 'Parang'],
    ['BARMM', 'SULU', 'Pata'],
    ['BARMM', 'SULU', 'Patikul'],
    ['BARMM', 'SULU', 'Siasi'],
    ['BARMM', 'SULU', 'Talipao'],
    ['BARMM', 'SULU', 'Tapul'],
    ['BARMM', 'SULU', 'Tongkil'],
    ['BARMM', 'TAWI-TAWI', 'Bongao'],
    ['BARMM', 'TAWI-TAWI', 'Languyan'],
    ['BARMM', 'TAWI-TAWI', 'Mapun'],
    ['BARMM', 'TAWI-TAWI', 'Panglima Sugala'],
    ['BARMM', 'TAWI-TAWI', 'Sapa-Sapa'],
    ['BARMM', 'TAWI-TAWI', 'Sibutu'],
    ['BARMM', 'TAWI-TAWI', 'Simunul'],
    ['BARMM', 'TAWI-TAWI', 'Sitangkai'],
    ['BARMM', 'TAWI-TAWI', 'South Ubian'],
    ['BARMM', 'TAWI-TAWI', 'Tandubas'],
    ['BARMM', 'TAWI-TAWI', 'Turtle Islands'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Dapitan City'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Dipolog City'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Bacungan'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Baliguian'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Godod'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Gutalac'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Jose Dalman'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Kalawit'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Katipunan'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'La Libertad'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Labason'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Liloy'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Manukan'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Mutia'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Piñan'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Polanco'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Pres. Manuel A. Roxas'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Rizal'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Salug'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Sergio Osmeña Sr.'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Siayan'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Sibuco'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Sibutad'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Sindangan'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Siocon'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Sirawai'],
    ['REGION IX', 'ZAMBOANGA DEL NORTE', 'Tampilisan'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Pagadian City'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Zamboanga City'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Aurora'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Bayog'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Dimataling'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Dinas'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Dumalinao'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Dumingag'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Guipos'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Josefina'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Kumalarang'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Labangan'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Lakewood'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Lapuyan'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Mahayag'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Margosatubig'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Midsalip'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Molave'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Pitogo'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Ramon Magsaysay'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'San Miguel'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'San Pablo'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Sominot'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Tabina'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Tambulig'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Tigbao'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Tukuran'],
    ['REGION IX', 'ZAMBOANGA DEL SUR', 'Vincenzo A. Sagun'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Alicia'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Buug'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Diplahan'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Imelda'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Ipil'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Kabasalan'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Mabuhay'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Malangas'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Naga'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Olutanga'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Payao'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Roseller Lim'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Siay'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Talusan'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Titay'],
    ['REGION IX', 'ZAMBOANGA SIBUGAY', 'Tungawan'],
    ['REGION X', 'BUKIDNON', 'Malaybalay City'],
    ['REGION X', 'BUKIDNON', 'Valencia City'],
    ['REGION X', 'BUKIDNON', 'Baungon'],
    ['REGION X', 'BUKIDNON', 'Cabanglasan'],
    ['REGION X', 'BUKIDNON', 'Damulog'],
    ['REGION X', 'BUKIDNON', 'Dangcagan'],
    ['REGION X', 'BUKIDNON', 'Don Carlos'],
    ['REGION X', 'BUKIDNON', 'Impasug-ong'],
    ['REGION X', 'BUKIDNON', 'Kadingilan'],
    ['REGION X', 'BUKIDNON', 'Kalilangan'],
    ['REGION X', 'BUKIDNON', 'Kibawe'],
    ['REGION X', 'BUKIDNON', 'Kitaotao'],
    ['REGION X', 'BUKIDNON', 'Lantapan'],
    ['REGION X', 'BUKIDNON', 'Libona'],
    ['REGION X', 'BUKIDNON', 'Malitbog'],
    ['REGION X', 'BUKIDNON', 'Manolo Fortich'],
    ['REGION X', 'BUKIDNON', 'Maramag'],
    ['REGION X', 'BUKIDNON', 'Pangantucan'],
    ['REGION X', 'BUKIDNON', 'Quezon'],
    ['REGION X', 'BUKIDNON', 'San Fernando'],
    ['REGION X', 'BUKIDNON', 'Sumilao'],
    ['REGION X', 'BUKIDNON', 'Talakag'],
    ['REGION X', 'CAMIGUIN', 'Catarman'],
    ['REGION X', 'CAMIGUIN', 'Guinsiliban'],
    ['REGION X', 'CAMIGUIN', 'Mahinog'],
    ['REGION X', 'CAMIGUIN', 'Mambajao'],
    ['REGION X', 'CAMIGUIN', 'Sagay'],
    ['REGION X', 'LANAO DEL NORTE', 'Iligan City'],
    ['REGION X', 'LANAO DEL NORTE', 'Bacolod'],
    ['REGION X', 'LANAO DEL NORTE', 'Baloi'],
    ['REGION X', 'LANAO DEL NORTE', 'Baroy'],
    ['REGION X', 'LANAO DEL NORTE', 'Kapatagan'],
    ['REGION X', 'LANAO DEL NORTE', 'Kauswagan'],
    ['REGION X', 'LANAO DEL NORTE', 'Kolambugan'],
    ['REGION X', 'LANAO DEL NORTE', 'Lala'],
    ['REGION X', 'LANAO DEL NORTE', 'Linamon'],
    ['REGION X', 'LANAO DEL NORTE', 'Magsaysay'],
    ['REGION X', 'LANAO DEL NORTE', 'Maigo'],
    ['REGION X', 'LANAO DEL NORTE', 'Matungao'],
    ['REGION X', 'LANAO DEL NORTE', 'Munai'],
    ['REGION X', 'LANAO DEL NORTE', 'Nunungan'],
    ['REGION X', 'LANAO DEL NORTE', 'Pantao Ragat'],
    ['REGION X', 'LANAO DEL NORTE', 'Pantar'],
    ['REGION X', 'LANAO DEL NORTE', 'Poona Piagapo'],
    ['REGION X', 'LANAO DEL NORTE', 'Salvador'],
    ['REGION X', 'LANAO DEL NORTE', 'Sapad'],
    ['REGION X', 'LANAO DEL NORTE', 'Sultan Naga Dimaporo'],
    ['REGION X', 'LANAO DEL NORTE', 'Tagoloan'],
    ['REGION X', 'LANAO DEL NORTE', 'Tangcal'],
    ['REGION X', 'LANAO DEL NORTE', 'Tubod'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Oroquieta City'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Ozamiz City'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Tangub City'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Aloran'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Baliangao'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Bonifacio'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Calamba'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Clarin'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Concepcion'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Don Victoriano Chiongbian'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Jimenez'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Lopez Jaena'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Panaon'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Plaridel'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Sapang Dalaga'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Sinacaban'],
    ['REGION X', 'MISAMIS OCCIDENTAL', 'Tudela'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Cagayan de Oro'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Gingoog City'],
    ['REGION X', 'MISAMIS ORIENTAL', 'El Salvador City'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Alubijid'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Balingasag'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Balingoan'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Binuangan'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Claveria'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Gitagum'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Initao'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Jasaan'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Kinoguitan'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Lagonglong'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Laguindingan'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Libertad'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Lugait'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Magsaysay'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Manticao'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Medina'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Naawan'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Opol'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Salay'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Sugbongcogon'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Tagoloan'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Talisayan'],
    ['REGION X', 'MISAMIS ORIENTAL', 'Villanueva'],
    ['REGION XI', 'DAVAO DEL NORTE', 'Island Garden City of Samal'],
    ['REGION XI', 'DAVAO DEL NORTE', 'Panabo City'],
    ['REGION XI', 'DAVAO DEL NORTE', 'Tagum City'],
    ['REGION XI', 'DAVAO DEL NORTE', 'Asuncion'],
    ['REGION XI', 'DAVAO DEL NORTE', 'Braulio E. Dujali'],
    ['REGION XI', 'DAVAO DEL NORTE', 'Carmen'],
    ['REGION XI', 'DAVAO DEL NORTE', 'Kapalong'],
    ['REGION XI', 'DAVAO DEL NORTE', 'New Corella'],
    ['REGION XI', 'DAVAO DEL NORTE', 'San Isidro'],
    ['REGION XI', 'DAVAO DEL NORTE', 'Santo Tomas'],
    ['REGION XI', 'DAVAO DEL NORTE', 'Talaingod'],
    ['REGION XI', 'DAVAO DEL SUR', 'Davao City'],
    ['REGION XI', 'DAVAO DEL SUR', 'Digos City'],
    ['REGION XI', 'DAVAO DEL SUR', 'Bansalan'],
    ['REGION XI', 'DAVAO DEL SUR', 'Don Marcelino'],
    ['REGION XI', 'DAVAO DEL SUR', 'Hagonoy'],
    ['REGION XI', 'DAVAO DEL SUR', 'Jose Abad Santos'],
    ['REGION XI', 'DAVAO DEL SUR', 'Kiblawan'],
    ['REGION XI', 'DAVAO DEL SUR', 'Magsaysay'],
    ['REGION XI', 'DAVAO DEL SUR', 'Malalag'],
    ['REGION XI', 'DAVAO DEL SUR', 'Malita'],
    ['REGION XI', 'DAVAO DEL SUR', 'Matanao'],
    ['REGION XI', 'DAVAO DEL SUR', 'Padada'],
    ['REGION XI', 'DAVAO DEL SUR', 'Santa Cruz'],
    ['REGION XI', 'DAVAO DEL SUR', 'Santa Maria'],
    ['REGION XI', 'DAVAO DEL SUR', 'Sarangani'],
    ['REGION XI', 'DAVAO DEL SUR', 'Sulop'],
    ['REGION XI', 'DAVAO ORIENTAL', 'Mati City'],
    ['REGION XI', 'DAVAO ORIENTAL', 'Baganga'],
    ['REGION XI', 'DAVAO ORIENTAL', 'Banaybanay'],
    ['REGION XI', 'DAVAO ORIENTAL', 'Boston'],
    ['REGION XI', 'DAVAO ORIENTAL', 'Caraga'],
    ['REGION XI', 'DAVAO ORIENTAL', 'Cateel'],
    ['REGION XI', 'DAVAO ORIENTAL', 'Governor Generoso'],
    ['REGION XI', 'DAVAO ORIENTAL', 'Lupon'],
    ['REGION XI', 'DAVAO ORIENTAL', 'Manay'],
    ['REGION XI', 'DAVAO ORIENTAL', 'San Isidro'],
    ['REGION XI', 'DAVAO ORIENTAL', 'Tarragona'],
    ['REGION XI', 'DAVAO DE ORO', 'Compostela'],
    ['REGION XI', 'DAVAO DE ORO', 'Laak'],
    ['REGION XI', 'DAVAO DE ORO', 'Mabini'],
    ['REGION XI', 'DAVAO DE ORO', 'Maco'],
    ['REGION XI', 'DAVAO DE ORO', 'Maragusan'],
    ['REGION XI', 'DAVAO DE ORO', 'Mawab'],
    ['REGION XI', 'DAVAO DE ORO', 'Monkayo'],
    ['REGION XI', 'DAVAO DE ORO', 'Montevista'],
    ['REGION XI', 'DAVAO DE ORO', 'Nabunturan'],
    ['REGION XI', 'DAVAO DE ORO', 'New Bataan'],
    ['REGION XI', 'DAVAO DE ORO', 'Pantukan'],
    ['REGION XII', 'COTABATO', 'Kidapawan City'],
    ['REGION XII', 'COTABATO', 'Alamada'],
    ['REGION XII', 'COTABATO', 'Aleosan'],
    ['REGION XII', 'COTABATO', 'Antipas'],
    ['REGION XII', 'COTABATO', 'Arakan'],
    ['REGION XII', 'COTABATO', 'Banisilan'],
    ['REGION XII', 'COTABATO', 'Carmen'],
    ['REGION XII', 'COTABATO', 'Kabacan'],
    ['REGION XII', 'COTABATO', 'Libungan'],
    ['REGION XII', 'COTABATO', 'M\'lang'],
    ['REGION XII', 'COTABATO', 'Magpet'],
    ['REGION XII', 'COTABATO', 'Makilala'],
    ['REGION XII', 'COTABATO', 'Matalam'],
    ['REGION XII', 'COTABATO', 'Midsayap'],
    ['REGION XII', 'COTABATO', 'Pigcawayan'],
    ['REGION XII', 'COTABATO', 'Pikit'],
    ['REGION XII', 'COTABATO', 'President Roxas'],
    ['REGION XII', 'COTABATO', 'Tulunan'],
    ['REGION XII', 'SOUTH COTABATO', 'General Santos City'],
    ['REGION XII', 'SOUTH COTABATO', 'Koronadal City'],
    ['REGION XII', 'SOUTH COTABATO', 'Banga'],
    ['REGION XII', 'SOUTH COTABATO', 'Lake Sebu'],
    ['REGION XII', 'SOUTH COTABATO', 'Norala'],
    ['REGION XII', 'SOUTH COTABATO', 'Polomolok'],
    ['REGION XII', 'SOUTH COTABATO', 'Santo Niño'],
    ['REGION XII', 'SOUTH COTABATO', 'Surallah'],
    ['REGION XII', 'SOUTH COTABATO', 'T\'boli'],
    ['REGION XII', 'SOUTH COTABATO', 'Tampakan'],
    ['REGION XII', 'SOUTH COTABATO', 'Tantangan'],
    ['REGION XII', 'SOUTH COTABATO', 'Tupi'],
    ['REGION XII', 'SULTAN KUDARAT', 'Tacurong City'],
    ['REGION XII', 'SULTAN KUDARAT', 'Bagumbayan'],
    ['REGION XII', 'SULTAN KUDARAT', 'Columbio'],
    ['REGION XII', 'SULTAN KUDARAT', 'Esperanza'],
    ['REGION XII', 'SULTAN KUDARAT', 'Isulan'],
    ['REGION XII', 'SULTAN KUDARAT', 'Kalamansig'],
    ['REGION XII', 'SULTAN KUDARAT', 'Lambayong'],
    ['REGION XII', 'SULTAN KUDARAT', 'Lebak'],
    ['REGION XII', 'SULTAN KUDARAT', 'Lutayan'],
    ['REGION XII', 'SULTAN KUDARAT', 'Palimbang'],
    ['REGION XII', 'SULTAN KUDARAT', 'President Quirino'],
    ['REGION XII', 'SULTAN KUDARAT', 'Sen. Ninoy Aquino'],
    ['REGION XII', 'SARANGANI', 'Alabel'],
    ['REGION XII', 'SARANGANI', 'Glan'],
    ['REGION XII', 'SARANGANI', 'Kiamba'],
    ['REGION XII', 'SARANGANI', 'Maasim'],
    ['REGION XII', 'SARANGANI', 'Maitum'],
    ['REGION XII', 'SARANGANI', 'Malapatan'],
    ['REGION XII', 'SARANGANI', 'Malungon'],
];

$stmt = $conn->prepare("INSERT INTO cities (REGION, PROVINCE, MUNICIPALITY, BARANGAY) VALUES (?, ?, ?, '')");
foreach ($cities as $city) {
    $stmt->bind_param("sss", $city[0], $city[1], $city[2]);
    $stmt->execute();
}

echo "Inserted " . count($cities) . " cities!";
